brew "caddy"
brew "erlang"
brew "elixir"
brew "fd"
brew "fzf"
brew "gcc"
brew "inotify-tools"
brew "neovim"
brew "postgresql@14", restart_service: :changed
brew "pure"
brew "solidity"
brew "watchman"
cask "font-0xproto-nerd-font"
cask "font-jetbrains-mono-nerd-font"
